Implemented QualifyLeadRequestHandler
delegateas/XrmMockup pull request #51
Opened 2018-04-16 13:03 UTC by Ladekarl

#30

2018-05-30 05:47 UTC, TomMalow requested changes
The test are missing asserts that verifies that data have been created in the mockup database. 

The Qualify lead process does not currently create any Opportunities and are missing some checks such as it should not be possible to add an existing account to the qualifying process with out requiring creation of a new Opportunity. 

Qualify lead does not handle any kind of duplicate detection when creating new account or contacts.

2018-05-30 05:47 UTC, TomMalow commented on src/XrmMockupShared/Requests/QualifyLeadRequestHandler.cs
> +            resp.Results["CreatedEntities"] = createdEntities;
You also need to create the entities in the mockup database. Currently you just respond with almost the same data as the user has requested. Additionally, you also need to update the state of the Lead to Qualified.

2018-05-30 05:47 UTC, TomMalow commented on tests/SharedTests/TestLeads.cs
> +        public void TestQualifyLeadRequestCreateAccountSuccess()
Missing assert that lead has been qualified and that a new account has been created

2018-05-30 05:47 UTC, TomMalow commented on tests/SharedTests/TestLeads.cs
> +        public void TestQualifyLeadRequestOpportunityCustomerIdSuccess()
Missing assert that lead has been qualified. This test should also fails as you need to also set CreateOpportunity if you want to set OpportunityCustomerId as it defines an existing account that the opportunity should point to

2018-05-30 05:47 UTC, TomMalow commented on tests/SharedTests/TestLeads.cs
> +        public void TestQualifyLeadRequestCreateContactSuccess()
Missing assert that lead has been qualified and check if a new contact have been created

2018-05-30 05:47 UTC, TomMalow commented on tests/SharedTests/TestLeads.cs
> +        public void TestQualifyLeadRequestSuccess()
Missing assert if the lead has been qualified

2018-05-30 05:47 UTC, TomMalow commented on tests/SharedTests/TestLeads.cs
> +        public void TestQualifyLeadRequestOpportunityCurrencyIdSuccess()
Missing assert that lead has been qualified. This test should also fails as you need to also set CreateOpportunity if you want to set OpportunityCurrencyId

2018-05-30 05:47 UTC, TomMalow commented on tests/SharedTests/TestLeads.cs
> +        public void TestQualifyLeadRequestCreateOpportunityAccountSuccess()
Missing assert that lead has been qualified and that a new Opportunity have been created and points to the existing account

2018-05-30 05:47 UTC, TomMalow commented on tests/SharedTests/TestLeads.cs
> +        public void TestQualifyLeadRequestCreateOpportunityContactSuccess()
Missing assert that lead has been qualified and that a new Opportunity have been created and points to the existing contact

2018-05-30 05:47 UTC, TomMalow commented on tests/SharedTests/TestLeads.cs
> +        public void TestQualifyLeadRequestCreateAllSuccess()
Missing assert that lead has been qualified and that a new Opportunity and Account have been created and that the opportunity points the the new account and existing contact

2018-05-30 05:47 UTC, TomMalow commented on src/XrmMockupShared/Requests/QualifyLeadRequestHandler.cs
> +                var contactAlreadyExists = db["contact"].Any(row => row["fullname"] != null && row["fullname"].Equals(lead["fullname"]));
I don't think Qualified Lead handles any kind of duplicate detection in CRM.

2018-05-30 05:47 UTC, TomMalow commented on src/XrmMockupShared/Requests/QualifyLeadRequestHandler.cs
> +                var accountAlreadyExists = db["account"].Any(row => row["name"] != null && row["name"].Equals(lead["fullname"]));
I don't think Qualified Lead handles any kind of duplicate detection in CRM.

2018-05-30 05:47 UTC, TomMalow commented on src/XrmMockupShared/Requests/QualifyLeadRequestHandler.cs
> +                var account = new Entity
Qualify lead uses some of the fields on the lead when creating the account. Such as the Company text field

2018-05-30 05:47 UTC, TomMalow commented on src/XrmMockupShared/Requests/QualifyLeadRequestHandler.cs
> +                var contact = new Entity
Qualify Lead uses fields on the lead when creating the contact such as Contact Name and Job title.

2026-07-09 06:18 UTC, mkholt commented
Implemented and released in #343

2026-07-09 06:18 UTC, closed without merging